# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: git pull build-tools
      uses: actions/checkout@v3
      with:
        repository: tony-507/build-tools
        path: tmp
    - name: Setup build-tools
      run: |
        mv tmp/build-tools .
        rm -rf tmp
        ln -sf build-tools/build-local.sh build-local.sh
    - name: Run build
      run: |
        ./build-local.sh
